feat: inverse pullrefresh
MateriiApps/pullrefresh pull request #4
Opened 2023-11-14 05:03 UTC by rushiiMachine

drag from the bottom of the screen instead

2023-11-14 14:55 UTC, wingio requested changes

2023-11-14 14:55 UTC, wingio commented on pullrefresh/src/commonMain/kotlin/dev/materii/pullrefresh/PullRefresh.kt
>          properties["enabled"] = enabled
should add one of these for the inverse property

2023-11-14 16:36 UTC, rushiiMachine commented
also spotted another issue seems to not work in a lazycol very well

2023-11-15 03:12 UTC, wingio approved these changes

2023-11-15 03:13 UTC, merged