Simplify composables and add PullRefreshLayout
MateriiApps/pullrefresh pull request #9
Opened 2023-12-25 14:58 UTC by X1nto

Also updates to the latest compose multiplatform and Kotlin

2023-12-25 17:31 UTC, rushiiMachine requested changes

2023-12-25 17:31 UTC, rushiiMachine commented on pullrefresh/src/commonMain/kotlin/dev/materii/pullrefresh/PullRefreshLayout.kt
> +            if (flipped) Alignment.BottomCenter else Alignment.TopCenter
this doesn't need to be remembered

2023-12-25 17:31 UTC, rushiiMachine commented on pullrefresh/src/commonMain/kotlin/dev/materii/pullrefresh/DragRefreshLayout.kt
> +            if (flipped) Alignment.BottomCenter else Alignment.TopCenter
doesn't need to be remembered

2023-12-25 17:32 UTC, X1nto commented on pullrefresh/src/commonMain/kotlin/dev/materii/pullrefresh/PullRefreshLayout.kt
> +            if (flipped) Alignment.BottomCenter else Alignment.TopCenter
Sure ig

2024-01-29 22:02 UTC, wingio approved these changes

2024-01-29 22:11 UTC, merged